## cartridge.properties for cartridge app_storefrontnext_base
#Wed Nov 05 2025 07:59:18
demandware.cartridges.app_storefront_base.multipleLanguageStorefront=true
demandware.cartridges.app_storefront_base.id=app_storefrontnext_base
demandware.cartridges.app_storefront_base.version=0.0.1