/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import type { AnalyticsEvent } from '@salesforce/storefront-next-runtime/events';
import type { EngagementAdapter, EngagementAdapterConfig } from '@/lib/adapters';
import type { ShopperProducts, ShopperSearch } from '@salesforce/storefront-next-runtime/scapi';
import Cookies from 'js-cookie';

export type ActiveDataConfig = EngagementAdapterConfig & {
    host: string;
    locale: string;
    siteUUID?: string;
    sourceCode?: string;
    siteCurrency?: string;
};

/**
 * Active Data product data entry
 */
type ActiveDataProductDataEntry = {
    productId: string;
    eventType: 'event3' | 'event4';
    isRecommendation: boolean;
};

/**
 * Active Data parameters data structure
 */
type ActiveDataParams = {
    baseParams: Map<string, string>;
    productData: ActiveDataProductDataEntry[];
};

/**
 * Get the value of the analytics cookie set on the server
 * The cookie name is 'dwac_' followed by a UUID that is a hash of the siteId
 *
 * @param siteId - The site ID to construct the specific cookie name.
 * @returns The cookie value or null if not found
 */
function getAnalyticsCookieValue(siteUUID: string): string | null {
    const cookieName = `dwac_${siteUUID}`;
    const value = Cookies.get(cookieName);
    return value || null;
}

/**
 * Get analytics context from dwac cookie or initialize it with default values
 *
 * The properties returned here are set similar to how analyticsContext
 * is initialized in the old active-data.js script
 *
 * If a dwac cookie exists, it's parsed to extract visitor, customer, and other context.
 * Otherwise, default values are used.
 *
 * @param config - The active data configuration
 * @returns The analytics context
 */
function getAnalyticsContext(config: ActiveDataConfig) {
    const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone || '';

    const cookieValue = getAnalyticsCookieValue(config.siteUUID || '');

    if (cookieValue == null) {
        // No cookie found, return default values
        return {
            visitorID: '__ANONYMOUS__',
            customer: '__ANONYMOUS__',
            siteCurrency: config.siteCurrency || 'USD',
            sourceCode: config.sourceCode || '',
            enabled: true,
            timeZone,
            dwEnabled: true,
        };
    }

    // NOTE: This branch is only reachable on a hybrid site as the dwac_* cookie is generated by ecom on SFRA / SG sites.
    // The dwac_* cookie is not set by PWA or sf-next.

    // Parse dwac cookie value (format: visitorID|repository|customer|sourceCode|siteCurrency|enabled|timeZone|dwEnabled)
    const tokens = cookieValue.split('|');

    return {
        visitorID: tokens[0] || '__ANONYMOUS__',
        repository: tokens[1],
        customer: tokens[2] || '__ANONYMOUS__',
        sourceCode: tokens[3] || config.sourceCode || '',
        siteCurrency: tokens[4] || config.siteCurrency || 'USD',
        enabled: tokens[5] === 'true',
        timeZone: tokens[6] || timeZone,
        dwEnabled: tokens[7] === 'true',
    };
}

/**
 * Custom URL encode to match Java URLEncoder behavior.
 * This is used to encode product IDs and other values that ecom expects to be
 * encoded as Java URLEncoder.encode(value, "UTF-8")
 *
 * This is based on the custom urlencode function in the old active-data.js script
 */
function urlEncode(value: string): string {
    const convertByte = (code: number): string => {
        if (code < 32) {
            return '';
        }
        return `%${code.toString(16).toUpperCase().padStart(2, '0')}`;
    };

    let encoded = '';
    for (let i = 0; i < value.length; i++) {
        const c = value.charCodeAt(i);
        if (
            (c >= 97 && c <= 122) || // a-z
            (c >= 65 && c <= 90) || // A-Z
            (c >= 48 && c <= 57) || // 0-9
            c === 46 || // .
            c === 45 || // -
            c === 42 || // *
            c === 95 // _
        ) {
            encoded += value.charAt(i);
        } else if (c === 32) {
            encoded += '+';
        } else if (c < 128) {
            encoded += convertByte(c);
        } else if (c >= 128 && c < 2048) {
            encoded += convertByte((c >> 6) | 0xc0);
            encoded += convertByte((c & 0x3f) | 0x80);
        } else if (c >= 2048 && c < 65536) {
            encoded += convertByte((c >> 12) | 0xe0);
            encoded += convertByte(((c >> 6) & 0x3f) | 0x80);
            encoded += convertByte((c & 0x3f) | 0x80);
        } else if (c >= 65536) {
            encoded += convertByte((c >> 18) | 0xf0);
            encoded += convertByte(((c >> 12) & 0x3f) | 0x80);
            encoded += convertByte(((c >> 6) & 0x3f) | 0x80);
            encoded += convertByte((c & 0x3f) | 0x80);
        }
    }
    return encoded;
}

/**
 * Get product ID from product or product search hit
 */
function getProductId(
    product: ShopperProducts.schemas['Product'] | ShopperSearch.schemas['ProductSearchHit']
): string | null {
    if ('id' in product && product.id) {
        return product.id;
    }
    if ('productId' in product && product.productId) {
        return product.productId;
    }
    return null;
}

/**
 * Create base active data parameters from the AnalyticsEvent.
 * These parameters are common to all active data events.
 *
 * These parameters were obtained from the active-data.js script used by PWA
 */
function createBaseParams(): ActiveDataParams {
    const baseParams = new Map<string, string>();

    // Use window.location.href instead of event.path to match the old script behavior
    // where the host is included in the path
    const path = window.location.href;

    // Basic page info
    baseParams.set('url', path);
    baseParams.set('res', `${screen.width}x${screen.height}`);
    baseParams.set('cookie', navigator.cookieEnabled ? '1' : '0');
    baseParams.set('ref', document.referrer || '');
    baseParams.set('title', document.title);

    // Plugin detection (all set to 0 for now, can be enhanced later)
    baseParams.set('pdf', '0');
    baseParams.set('qt', '0');
    baseParams.set('realp', '0');
    baseParams.set('wma', '0');
    baseParams.set('dir', '0');
    baseParams.set('fla', '0');
    baseParams.set('java', '0');
    baseParams.set('gears', '0');
    baseParams.set('ag', '0');

    return {
        baseParams,
        productData: [],
    };
}

/**
 * Helper function for adding product data to params
 */
function addProductDataToParams(
    params: ActiveDataParams,
    products: Array<ShopperProducts.schemas['Product'] | ShopperSearch.schemas['ProductSearchHit']>,
    eventType: 'event3' | 'event4',
    isRecommendation = false
) {
    for (const product of products) {
        const productId = getProductId(product);
        if (!productId) continue;

        params.productData.push({
            productId,
            eventType,
            isRecommendation,
        });
    }
}

/**
 * Get the event type string based on the analytics event type
 *
 * These event type strings were obtained from the active-data.js script used by PWA
 *
 * @returns 'event4' for ViewProduct, 'event3' for ViewCategory, ViewSearch, and ViewRecommender
 */
function getEventTypeString(
    eventType: 'view_product' | 'view_category' | 'view_search' | 'view_recommender'
): 'event3' | 'event4' {
    switch (eventType) {
        case 'view_product':
            return 'event4'; // In active-data.js, event4 is used for product views
        case 'view_category':
        case 'view_search':
        case 'view_recommender':
            return 'event3'; // In active-data.js, event3 is used for product impressions, recommendations, and category views
    }
}

/**
 * Set active data parameters based on event type and active data context
 */
function extractActiveDataParamsFromEvent(event: AnalyticsEvent): ActiveDataParams {
    const params = createBaseParams();

    switch (event.eventType) {
        case 'view_page': {
            // For view_page events, just send base params (no product/search/category data)
            // The path is already included in base params via the 'url' parameter
            // No pcat is set for generic page views
            break;
        }

        // This creates an Active Data product view
        case 'view_product': {
            const viewProductEvent = event;
            const productId = getProductId(viewProductEvent.product);
            params.baseParams.set('pcat', (viewProductEvent.product.categoryId as string) || '');
            if (productId) {
                addProductDataToParams(params, [viewProductEvent.product], getEventTypeString('view_product'));
            }
            break;
        }

        // This creates an Active Data product impression
        case 'view_search': {
            const viewSearchEvent = event;
            params.baseParams.set('pst-q', viewSearchEvent.searchInputText);
            params.baseParams.set('pst-show', viewSearchEvent.searchResults.length > 0 ? 'true' : 'false');
            params.baseParams.set('pst-sort', viewSearchEvent.sort || '');
            params.baseParams.set(
                'pst-refs',
                viewSearchEvent.refinements ? JSON.stringify(viewSearchEvent.refinements) : ''
            );

            if (viewSearchEvent.searchResults.length > 0) {
                addProductDataToParams(params, viewSearchEvent.searchResults, getEventTypeString('view_search'));
            }
            break;
        }

        // This creates an Active Data product impression
        case 'view_category': {
            const viewCategoryEvent = event;
            const categoryId = viewCategoryEvent.category.id || '';
            params.baseParams.set('pcat', categoryId);
            params.baseParams.set('pst-show', viewCategoryEvent.searchResults.length > 0 ? 'true' : 'false');
            params.baseParams.set('pst-sort', viewCategoryEvent.sort || '');
            params.baseParams.set(
                'pst-refs',
                viewCategoryEvent.refinements ? JSON.stringify(viewCategoryEvent.refinements) : ''
            );

            if (viewCategoryEvent.searchResults.length > 0) {
                addProductDataToParams(params, viewCategoryEvent.searchResults, getEventTypeString('view_category'));
            }
            break;
        }

        // This creates an Active Data product recommendation
        case 'view_recommender': {
            const viewRecommenderEvent = event;
            if (viewRecommenderEvent.products.length > 0) {
                addProductDataToParams(
                    params,
                    viewRecommenderEvent.products,
                    getEventTypeString('view_recommender'),
                    true
                );
            }
            break;
        }

        default:
            // For other event types, just send base params
            break;
    }

    return params;
}

/**
 * Get do not track cookie value from dw_dnt cookie
 */
function getDoNotTrackCookie(): string | null {
    const cookieValue = Cookies.get('dw_dnt');
    // Return the value if it exists and is '0' or '1', otherwise return null
    return cookieValue === '0' || cookieValue === '1' ? cookieValue : null;
}

/**
 * Create context parameters from analytics context
 * Context params include: dwac, cmpn, tz, pcc, pct
 *
 * @param analyticsContext - The analytics context
 */
function createContextParams(config: ActiveDataConfig): Map<string, string> {
    const analyticsContext = getAnalyticsContext(config);
    const contextParams = new Map<string, string>();

    // Generate dwac ID for the event
    // This matches the old script behavior where id = Math.random() is called once per logPageView
    const dwacId = Math.random().toString();
    contextParams.set('dwac', dwacId);

    if (analyticsContext.dwEnabled) {
        contextParams.set('cmpn', analyticsContext.sourceCode);
        contextParams.set('tz', analyticsContext.timeZone);
        contextParams.set('pcc', analyticsContext.siteCurrency);
        contextParams.set('pct', analyticsContext.customer);
    }

    return contextParams;
}

function createUrlWithContextParams(baseUrl: string, config: ActiveDataConfig): string {
    const contextParams = createContextParams(config);

    let url = baseUrl;
    let isFirstParam = true;

    // Add context params to the initial URL
    for (const [key, value] of contextParams.entries()) {
        const separator = isFirstParam ? '?' : '&';
        url += `${separator}${key}=${encodeURIComponent(value)}`;
        isFirstParam = false;
    }
    return url;
}

/**
 * Split URL parameters into multiple requests if they exceed MAX_URL_LENGTH
 * This matches the behavior of the old createUrls function in the active-data.js script
 */
function createActiveDataUrls(baseUrl: string, params: ActiveDataParams, config: ActiveDataConfig): string[] {
    const MAX_URL_LENGTH = 2000;
    const urls: string[] = [];

    // Initialize the starting URL. This part of the URL will remain constant across all URLs created for the same event.
    const urlWithContextParams = createUrlWithContextParams(baseUrl, config);

    let url = urlWithContextParams;

    // Add base parameters
    for (const [key, value] of params.baseParams.entries()) {
        // Special encoding for certain keys
        let encodedValue: string;
        if (key === 'pst-q') {
            encodedValue = urlEncode(value);
        } else {
            encodedValue = encodeURIComponent(value);
        }

        const paramStr = `${key}=${encodedValue}`;

        // If adding the parameter would exceed the MAX_URL_LENGTH, push the current URL and start a new one
        if (url.length + paramStr.length + 1 > MAX_URL_LENGTH) {
            urls.push(url);
            url = urlWithContextParams;
        }

        url += `&${paramStr}`;
    }

    // Then, add product entries (pid, pev, evr4 together)
    // We want to make sure a product entry is not split across multiple URLs
    for (let count = 0; count < params.productData.length; count++) {
        const product = params.productData[count];
        // Use custom urlEncode for product IDs to match Java URLEncoder behavior
        const pidStr = `pid-${count}=${urlEncode(product.productId)}`;
        const pevStr = `&pev-${count}=${encodeURIComponent(product.eventType)}`;
        const evr4Str = product.isRecommendation ? `&evr4-${count}=${encodeURIComponent('Yes')}` : '';
        const totalProductStr = pidStr + pevStr + evr4Str;

        // Check if adding product string would exceed max length (account for & separator)
        // If it does, push the current URL and start a new one
        if (url.length + totalProductStr.length + 1 > MAX_URL_LENGTH) {
            urls.push(url);
            url = urlWithContextParams;
        }

        url += `&${totalProductStr}`;
    }

    // Add do not track cookie to the last URL
    // This follows the behavior of the old createUrls function in the active-data.js script
    // where DNT is only sent once at the end
    // If DNT is not present, don't add it to the URL. In this case, ecom assumes tracking is allowed.
    const dntValue = getDoNotTrackCookie();
    if (dntValue) {
        url += `&dw_dnt=${encodeURIComponent(dntValue)}`;
    }

    // Always push the final URL (matches old script behavior which always pushes the final request)
    // This ensures we always return at least one URL with context params
    urls.push(url);

    return urls;
}

function validateActiveDataConfig(config: ActiveDataConfig): { valid: boolean; errors: string[] } {
    const errors: string[] = [];
    if (!config.host || config.host.trim() === '') {
        errors.push(`Missing required field: host`);
    }
    if (!config.siteId || config.siteId.trim() === '') {
        errors.push(`Missing required field: siteId`);
    }
    if (!config.locale || config.locale.trim() === '') {
        errors.push(`Missing required field: locale`);
    }
    return { valid: errors.length === 0, errors };
}

/**
 * Create an Active Data adapter function that implements the Adapter interface
 */
export function createActiveDataAdapter(config: ActiveDataConfig): EngagementAdapter {
    const validConfig = validateActiveDataConfig(config);
    if (!validConfig.valid) {
        const errorMessage = `Active Data adapter configuration is invalid: ${validConfig.errors.join('; ')}`;
        throw new Error(errorMessage, { cause: validConfig.errors });
    }

    return {
        name: 'active-data',
        sendEvent: async (event: AnalyticsEvent): Promise<unknown> => {
            // Don't send events that are not enabled for this adapter
            if (!config.eventToggles[event.eventType]) return Promise.resolve({});

            // Only handle view_page, view_product, view_search, view_category, and view_recommender for now
            if (
                event.eventType !== 'view_page' &&
                event.eventType !== 'view_product' &&
                event.eventType !== 'view_search' &&
                event.eventType !== 'view_category' &&
                event.eventType !== 'view_recommender'
            ) {
                return Promise.resolve({});
            }

            const activeDataEndpoint = `${config.host}/on/demandware.store/Sites-${config.siteId}-Site/${config.locale}/__Analytics-Start`;

            const params = extractActiveDataParamsFromEvent(event);
            const urls = createActiveDataUrls(activeDataEndpoint, params, config);
            for (const url of urls) {
                navigator.sendBeacon(url);
            }

            return Promise.resolve({});
        },
    };
}
